title: Blog - ZK's site
description: This is the blog of Kevin Li, which is powered by Jekyll.
url: http://www.zhuolikevin.xyz/blog/
baseurl: /blog

sass:
  sass_dir: _sass

paginate: 5
paginate_path: /page:num/

# Build settings
destination: ../mysite/public/blog
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
